// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn8wgP00EPHiXLR4rnbcg2VMAsnpEeiYQ',
    appId: '1:1023500283433:web:ec87116d252b93a8bf3638',
    messagingSenderId: '1023500283433',
    projectId: 'machinetest-f7ac5',
    authDomain: 'machinetest-f7ac5.firebaseapp.com',
    storageBucket: 'machinetest-f7ac5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiKCPgfXorMhepNIeMeyo_ZR_FxIvPpIc',
    appId: '1:1023500283433:android:8d76409368bfaaa2bf3638',
    messagingSenderId: '1023500283433',
    projectId: 'machinetest-f7ac5',
    storageBucket: 'machinetest-f7ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALT5F8Lzy6EcRMqaHFsQjzdtDga1vSO0k',
    appId: '1:1023500283433:ios:2d2b2a94abede0acbf3638',
    messagingSenderId: '1023500283433',
    projectId: 'machinetest-f7ac5',
    storageBucket: 'machinetest-f7ac5.appspot.com',
    iosBundleId: 'com.example.realestateUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALT5F8Lzy6EcRMqaHFsQjzdtDga1vSO0k',
    appId: '1:1023500283433:ios:1dac7c82adfa1734bf3638',
    messagingSenderId: '1023500283433',
    projectId: 'machinetest-f7ac5',
    storageBucket: 'machinetest-f7ac5.appspot.com',
    iosBundleId: 'com.example.realestateUi.RunnerTests',
  );
}
